# 项目端口号
server:
  port: 9999

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      ui:
        title: 'BallCat Monitor'

# 请求Actuator加解密密钥
monitor:
  secret-id: 'ballcat-monitor'
  secret-key: '=BallCat-Monitor'

ballcat:
  # actuator 加解密密钥
  actuator:
    auth: true
    secret-id: 'ballcat-monitor'
    secret-key: '=BallCat-Monitor'