server:
  port: 8080

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
  boot:
    admin:
      client:
        url: http://ballcat-monitor:9999
        username: admin
        password: 123456

ballcat:
  redis:
    key-prefix: 'ballcat:'
  # actuator 加解密密钥
  actuator:
    auth: true
    secret-id: 'ballcat-monitor'
    secret-key: '=BallCat-Monitor'

security:
  oauth2:
    ignore-urls:
      - /public/**
      - /actuator/**
      - /doc.html
      - /v2/api-docs
      - /swagger-resources/**
      - /swagger-ui.html**
      - /webjars/**
      - /bycdao-ui/**
      - favicon.ico


# 暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# 密码加解密密钥
password:
  secret-key: '==BallCat-Auth=='

# 定时任务相关配置
xxl:
  job:
    admin:
      addresses: http://ballcat-job:8888/xxl-job-admin # xxl-job-admin 接口地址
    executor:
      port: 8081 #通讯端口
      appName: ballcat-admin-jobs
      logretentiondays: 30 #日志保留天数


swagger:
  title: BallCat-Admin Docs
  group-name: ballcat-admin
  description: BallCat 后台管理服务Api文档
  version: 0.0.1
  license: Powered By BallCat
  licenseUrl: http://www.ballcat.cn/
  terms-of-service-url: http://www.ballcat.cn/
  contact:
    name: Hccake
    email: chengbohua@foxmail.com
    url: https://github.com/Hccake
  authorization:
    name: BallCat OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://ballcat-admin:8080/oauth/token
  aggregator:
    provider-resources:
      - {name: ballcat-api,  url: http://ballcat-api:9090/v2/api-docs, swagger-version: 2.0}
